configurations:
  bat:
    pacman: [bat]
    links: [.config/bat]
  dunst:
    pacman: [dunst]
    links: [.config/dunstg]
  eza:
    pacman: [eza]
    links: [.config/eza]
  fish:
    links: [.config/fish]
    pacman:
      - fish
      - fisher
      - bat
      - eza
      - fzf
      - pyenv
      - thefuck
      - tmux
      - yq
  github:
    pacman: [github-cli]
    links: [.config/gh]
  git:
    pacman: [git]
    links: [.gitconfig]
  hypr:
    links: [.config/hypr]
    pacman:
      - hyprland
      - hyprlock
      - dunst
      - kitty
      - brightnessctl
      - rofi-wayland
      - sddm
      - uwsm
      - wireplumber
      - xdg-desktop-portal-hyprland
    aur: [wlogout]
  kitty:
    pacman: [kitty]
    links: [.config/kitty]
  lazygit:
    pacman: [lazygit]
    links: [.config/lazygit]
  nvim:
    pacman:
      - nvim
      - fd
      - gcc
      - jdk21-openjdk
      - lazygit
      - luarocks
      - markdownlint-cli2
      - npm
      - python-neovim
      - python-pip
    aur: [ast-grep]
    links: [.config/nvim]
  qutebrowser:
    pacman: [qutebrowser]
    links: [.config/qutebrowser]
  rustup:
    pacman: [rustup]
    folders:
      - .cargo
      - .rustup
    links:
      - .cargo/.crates.toml
      - .cargo/config.toml
      - .rustup/settings.toml
  sdkman:
    pacman: [unzip, zip]
  ssh:
    pacman: [openssh]
    folders:
      - .ssh
      - .ssh/config.d
    links:
      - .ssh/config
  tmux:
    pacman: [tmux]
    links: [.config/tmux]
  wlogout:
    aur: [wlogout]
    links: [.config/wlogout]
profiles:
  desktop:
    symlinks:
      - src: .config/kitty/__lenovo27.conf
        dest: .config/kitty/override.conf
      - src: .config/hypr/profiles/nvidia.conf
        dest: .config/hypr/envs.conf
      - src: .config/dunst/__lenovo27.conf
        dest: .config/dunst/dunstrc
  laptop:
    symlinks:
      - src: .config/kitty/__lenovo_laptop.conf
        dest: .config/kitty/override.conf
      - src: .config/hypr/profiles/dummy.conf
        dest: .config/hypr/envs.conf
        # TODO: dunst
default_installs:
  - bat
  - dunst
  - eza
  - fish
  - git
  - github
  - hypr
  - kitty
  - lazygit
  - nvim
  - qutebrowser
  - rustup
  - sdkman
  - ssh
  - tmux
  # - wlogout
