configurations:
  bat:
    packages: [bat]
    links: [.config/bat]
  eza:
    packages: [eza]
    links: [.config/eza]
  fish:
    links: [.config/fish]
    packages:
      - fish
      - fisher
      - bat
      - eza
      - fzf
      - pyenv
      - thefuck
      - tmux
      - yq
  github:
    packages: [github-cli]
    links: [.config/gh]
  git:
    packages: [git]
    links: [.gitconfig]
  hypr:
    links: [.config/hypr]
    packages:
      - hyprland
      - hyprlock
      - kitty
      - brightnessctl
      - rofi-wayland
      - wireplumber
      - wlogout
  kitty:
    packages: [kitty]
    links: [.config/kitty]
  lazygit:
    packages: [lazygit]
    links: [.config/lazygit]
  nvim:
    packages:
      - nvim
      # - ast-grep
      - fd
      - gcc
      - jdk21-openjdk
      - lazygit
      - luarocks
      - markdownlint-cli2
      - npm
      - python-neovim
      - python-pip
    links: [.config/nvim]
  qutebrowser:
    packages: [qutebrowser]
    links: [.config/qutebrowser]
  rustup:
    packages: [rustup]
    folders:
      - .cargo
      - .rustup
    links:
      - .cargo/.crates.toml
      - .cargo/config.toml
      - .rustup/settings.toml
  sdkman:
    packages: [unzip, zip]
  ssh:
    packages: [openssh]
    folders:
      - .ssh
      - .ssh/config.d
    links:
      - .ssh/config
  tmux:
    packages: [tmux]
    links: [.config/tmux]
  wlogout: # TODO: AUR
    links: [.config/wlogout]
