---
- name: Install dotfiles
  hosts: localhost
  become: true
  vars:
    user: sotoestevez
    packages:
    - bat
    - eza
    - fish
    - fzf
    - markdownlint-cli2
    - nvim
    - pyenv
    - thefuck
    - tmux
    - yq
    configurations:
      dotconfig:
      - bat
      - eza
      - fish
      - gh
      - hypr
      - kitty
      - lazygit
      - nvim
      - qutebrowser
      - tmux
      - wlogout

  tasks:
  - name: Install required packages
    pacman:
      name: "{{ packages }}"
      state: present
      update_cache: yes
  - name: Check for SDKMAN
    stat:
      path: "/home/{{ user }}/.sdkman"
    register: sdkman
    when: '"fish" in packages'
  - name:
    debug:
      msg: "{{ sdkman }}"
  - name: Install SDKMAN
    become_user: "{{ user }}"
    shell: |
        curl -s "https://get.sdkman.io" | bash
    when: not sdkman.stat.exists
  - name: Check .config directory
    become_user: "{{ user }}"
    file:
      name: "/home/{{ user }}/.config"
      state: directory
  - name: Remove old .config configurations
    become_user: "{{ user }}"
    file:
      name: "/home/{{ user }}/.config/{{ item }}"
      state: absent
    loop: '{{ configurations["dotconfig"] }}'
  - name: Copy .config configurations
    become_user: "{{ user }}"
    file:
      src: "/home/{{ user }}/dotfiles/.config/{{ item }}"
      dest: "/home/{{ user }}/.config/{{ item }}"
      state: link
    loop: '{{ configurations["dotconfig"] }}'
