---
- name: Install dotfiles
  hosts: localhost
  become: true
  vars:
    fish_plugins: "{{ lookup('file', './.config/fish/fish_plugins') | split | join(' ') }}"
    user: sotoestevez
  vars_files:
    - config.yml

  tasks:
    # TODO:install yay, install yay packages
    - name: Check .config directory
      become_user: "{{ user }}"
      file:
        name: "$HOME/.config"
        state: directory
    - name: Copy configurations
      include_tasks:
        file: playbooks/configure.yml
      loop: "{{ lookup('dict', configurations) }}" # filter dict by active var
      loop_control:
        label: "{{ item.key }}"
        loop_var: config
    - name: Install SDKMAN
      include_tasks:
        file: playbooks/sdkman.yml
      when: '"fish" in configurations.keys()'
    - name: Install fish plugins
      become_user: "{{ user }}"
      shell: 'fish -c "fisher_path=$HOME/.local/share/fish/plugins fisher install {{ fish_plugins }}"'
      when: '"fish" in configurations.keys()'
