---
- name: Install dotfiles
  hosts: localhost
  become: true
  vars:
    user: sotoestevez
    packages:
    - bat
    - eza
    - fish
    - fzf
    - markdownlint-cli2
    - nvim
    - pyenv
    - thefuck
    - tmux
    - yq
    configurations:
      - name: bat
        type: .config
      - name: cargo
        type: nested
        files:
          - .crates.toml
          - config.toml
      - name: eza
        type: .config
      - name: fish
        type: .config
      - name: gh
        type: .config
      - name: hypr
        type: .config
      - name: kitty
        type: .config
      - name: lazygit
        type: .config
      - name: nvim
        type: .config
      - name: qutebrowser
        type: .config
      - name: rustup
        type: nested
        files:
          - settings.toml
      - name: ssh
        type: nested
        files:
          - config
        folders:
          - config.d
      - name: tmux
        type: .config
      - name: wlogout
        type: .config

  tasks:
  - name: Install required packages
    pacman:
      name: "{{ packages }}"
      state: present
      update_cache: yes
  - name: Check for SDKMAN
    stat:
      path: "/home/{{ user }}/.sdkman"
    register: sdkman
    when: '"fish" in packages'
  - name:
    debug:
      msg: "{{ sdkman }}"
  - name: Install SDKMAN
    become_user: "{{ user }}"
    shell: |
        curl -s "https://get.sdkman.io" | bash
    when: not sdkman.stat.exists
      # todo extract to playbook
  - name: Check .config directory
    become_user: "{{ user }}"
    file:
      name: "/home/{{ user }}/.config"
      state: directory
  - name: Remove old .config configurations
    become_user: "{{ user }}"
    file:
      name: "/home/{{ user }}/.config/{{ item['name'] }}" #map to name?
      state: absent
    loop: '{{ configurations | selectattr("type","equalto",".config") }}'
  - name: Link .config configurations
    become_user: "{{ user }}"
    file:
      src: "/home/{{ user }}/dotfiles/.config/{{ item['name'] }}"
      dest: "/home/{{ user }}/.config/{{ item['name'] }}"
      state: link
    loop: '{{ configurations | selectattr("type","equalto",".config") }}'
  - name: Symlink by items
    include_tasks:
      file: playbooks/nested_symlink.yml
    loop: '{{ configurations | selectattr("type","equalto","nested") }}'
    loop_control:
      loop_var: configuration
      label: "{{ configuration.name }}"

