---
- name: Install dotfiles
  hosts: localhost
  become: true
  vars_files:
    - config.yml
  vars:
    fresh_install: false
    install: "{{ default_installs | join(',' ) }}"
    fish_plugins: "{{ lookup('file', './.config/fish/fish_plugins') | split | join(' ') }}"
    user: sotoestevez

  tasks:
    # TODO:install yay packages
    - name: Install yay
      include_tasks:
        file: playbooks/yay.yml
      when: "{{ fresh_install }}"
    - name: Check .config directory
      become_user: "{{ user }}"
      file:
        name: "$HOME/.config"
        state: directory
    - name: Copy configurations
      include_tasks:
        file: playbooks/configure.yml
      loop: "{{ install | split(',') | map('extract', configurations) }}"
      loop_control:
        loop_var: config
    - name: Install SDKMAN
      include_tasks:
        file: playbooks/sdkman.yml
      when: '"sdkman" in install'
    - name: Install fish plugins
      become_user: "{{ user }}"
      shell: 'fish -c "fisher_path=$HOME/.local/share/fish/plugins fisher install {{ fish_plugins }}"'
      when: '"fish" in configurations.keys()'
