---
- name: Install dotfiles
  hosts: localhost
  become: true
  vars:
    user: sotoestevez
  vars_files:
    - config.yml

  tasks:
    # TODO:install fisher plugins, install yay, install yay packages

  - name: Install required packages
    pacman:
      name: "{{ packages }}"
      state: present
      update_cache: yes

  - name: Check for SDKMAN
    stat:
      path: "/home/{{ user }}/.sdkman"
    register: sdkman
    when: '"fish" in packages'
  - name: Install SDKMAN
    become_user: "{{ user }}"
    shell: |
        curl -s "https://get.sdkman.io" | bash
    when: not sdkman.stat.exists

  - name: Check .config directory
    become_user: "{{ user }}"
    file:
      name: "/home/{{ user }}/.config"
      state: directory
  - name: Symlink by folders
    include_tasks:
      file: playbooks/folder_symlink.yml
    loop: '{{ configurations | selectattr("type","equalto","folder") }}'
    loop_control:
      loop_var: configuration
      label: "{{ configuration.name }}"

  - name: Symlink by files
    include_tasks:
      file: playbooks/nested_symlink.yml
    loop: '{{ configurations | selectattr("type","equalto","nested") }}'
    loop_control:
      loop_var: configuration
      label: "{{ configuration.name }}"

  - name: Symlink by files
    include_tasks:
      file: playbooks/file_symlink.yml
    loop: '{{ configurations | selectattr("type","equalto","file") }}'
    loop_control:
      label: "{{ item.name }}"

