---
- name: Install dotfiles
  hosts: localhost
  become: true
  vars:
    user: sotoestevez
    packages:
    - bat
    - eza
    - fish
    - fzf
    - markdownlint-cli2
    - nvim
    - pyenv
    - thefuck
    - tmux
    - yq

  tasks:
  - name: Install required packages
    pacman:
      name: "{{ packages }}"
      state: present
      update_cache: yes
  - name: Check for SDKMAN
    stat:
      path: "/home/{{ user }}/.sdkman"
    register: sdkman
    when: '"fish" in packages'
  - name:
    debug:
      msg: "{{ sdkman }}"
  - name: Install SDKMAN
    become_user: "{{ user }}"
    shell: |
        curl -s "https://get.sdkman.io" | bash
    when: not sdkman.stat.exists
