#!/usr/bin/env bash

echo "Swapping the dotfiles repo to ssh"
yadm remote set-url origin "git@github.com:kriogenia/dotfiles.git"

echo "Building bat cache"
bat cache --build

# TODO: divide in bootstrap.d scripts

pkgs=$HOME/.local/state/dotfiles
if [ "$(awk -F'=' '/^ID/ {print $2}' /etc/os-release)" = "arch" ]; then
    echo "Found an ArchLinux distribution"

    echo "Installing Arch packages"
    sudo pacman --noconfirm -S $(cat $pkgs/pacman.lst)

    echo "Installing yay as AUR helper"
    git clone https://aur.archlinux.org/yay.git /tmp/yay
    cd /tmp/yay
    makepkg -si

    echo "Installing AUR packages"
    sudo yay --noconfirm -S $(cat $pkgs/yay.lst)

    # TODO: this could be extracted to only required flatpak
    echo "Installing flatpaks"
    sudo flatpak -y install $(cat $pkgs/flatpak.lst)
fi

echo "Installing fish plugins"
fish -c "cat $HOME/.config/fish/fish_plugins | fisher install -"


# if yadm config --get-all local.class | grep -q "class": then echo "do"; fi
