#!/usr/bin/env bash

echo "Swapping the dotfiles repo to ssh"
yadm remote set-url origin "git@github.com:kriogenia/dotfiles.git"

# install/check required packages

echo "Building bat cache"
bat cache --build
