# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

gui:
  theme:
    activeBorderColor:
      - '#c6a0f6'
      - bold
    inactiveBorderColor:
      - '#a5adcb'
    searchingActiveBorderColor:
      - '#eed49f'
    optionsTextColor:
      - '#8aadf4'
    selectedLineBgColor:
      - '#363a4f'
    cherryPickedCommitFgColor:
      - '#c6a0f6'
    cherryPickedCommitBgColor:
      - '#494d64'
    markedBaseCommitFgColor:
      - '#8aadf4'
    markedBaseCommitBgColor:
      - '#eed49f'
    unstagedChangesColor:
      - '#ed8796'
    defaultFgColor:
      - '#cad3f5'
  authorColors:
    '*': '#b7bdf8'
