[v1]
"aoc-cli 0.5.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["aoc"]
"cargo-bump 1.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-bump"]
"cargo-expand 1.0.9 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-expand"]
"du-dust 0.8.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["dust"]
"exa 0.10.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["exa"]
"mdbook 0.4.21 (registry+https://github.com/rust-lang/crates.io-index)" = ["mdbook"]
"ripgrep 13.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rg"]
"tauri-cli 1.0.0-rc.10 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-tauri"]
"trunk 0.15.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["trunk"]
"ytop 0.6.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["ytop"]
