[v1]
"cargo-expand 1.0.106 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-expand"]
"cargo-generate 0.23.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-generate"]
