[v1]
"cargo-expand 1.0.106 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-expand"]
"cargo-generate 0.23.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-generate"]
"leptosfmt 0.1.33 (registry+https://github.com/rust-lang/crates.io-index)" = ["leptosfmt"]
"trunk 0.21.14 (registry+https://github.com/rust-lang/crates.io-index)" = ["trunk"]
