# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Windowrules Configuration                ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Ignore maximize requests from apps.
windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

# Fix some dragging issues with XWayland
windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Floating windows
windowrule = match:class ^(org.pulseaudio.pavucontrol), float true
windowrule = match:class ^()$, match:title ^(Picture in picture)$, float true
windowrule = match:class ^()$, match:title ^(Save File)$, float true
windowrule = match:class ^()$, match:title ^(Open File)$, float true
windowrule = match:class ^(blueman-manager)$, float true
windowrule = match:class ^(xdg-desktop-portal-gtk|xdg-desktop-portal-kde|xdg-desktop-portal-hyprland)(.*)$, float true
windowrule = match:class ^(polkit-gnome-authentication-agent-1|hyprpolkitagent|org.org.kde.polkit-kde-authentication-agent-1)(.*)$, float true
windowrule = match:class ^(CachyOSHello)$, float true
windowrule = match:class ^(zenity)$, float true
windowrule = match:class ^()$, match:title ^(Steam - Self Updater)$, float true

# Increase the opacity
windowrule = match:class ^(thunar|nemo)$, opacity 0.92
windowrule = match:class ^(discord|webcord)$, opacity 0.96
windowrule = match:title ^(QQ|Telegram)$, opacity 0.95

# General window rules
windowrule = match:title ^(imv|danmufloat|termfloat|nemo|ncmpcpp)$, float true
windowrule = match:title ^(imv|danmufloat|termfloat|nemo|ncmpcpp)$, move 25%-
windowrule = match:title ^(imv|danmufloat|termfloat|nemo|ncmpcpp)$, size 960 520
windowrule = match:title ^(danmufloat)$, pin true
windowrule = match:title ^(danmufloat|termfloat)$, rounding 5
windowrule = match:class ^(kitty|Alacritty)$, animation slide right
windowrule = match:class ^(org.mozilla.firefox)$, no_blur true
windowrule = match:class ^(mpv)$, fullscreen true

windowrule {
  name = floating-windows-decoration
  match:float = true
  match:workspace = w[fv1-10]
 
  border_size = 2
  border_color = $cachylblue
  rounding = 8
}

windowrule {
  name = tiling-windows-decoration
  match:float = false
  match:workspace = w[fv1-10]
 
  border_size = 3
  rounding = 4
}

windowrule {
  name = special-workspace-belong
  match:class = ^(discord|equibop|vesktop|whatsapp)$

  workspace = special:communication
}

windowrule {
  name = picture-in-picture
  match:title = ^(Picture-in-Picture)$

  float = true
  size = 960 540
  move = 25%-
}

windowrule {
  name = ship-log
  match:class = ^(fastfetch)$

  float = true
  size = 1440 720
}

# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                  Workspace Rules Configuration              ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

workspace = w[tv1-10], gapsout:5, gapsin:3
workspace = f[1], gapsout:5, gapsin:3

workspace = special:communication, on-created-empty:exec $run discord.desktop

# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Layer Rules Configuration                ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

layerrule = match:namespace logout_dialog, animation slide top
layerrule = match:namespace waybar, animation slide down
layerrule = match:namespace wallpaper, animation fade 50%
