[ui.window.box]
width = 400
min_width = 400
max_width = 400
height = 400
min_height = 400
max_height = 400

# List constraints are critical - without these, the window shrinks when empty
[ui.window.box.scroll.list]
height = 300
min_height = 300
max_height = 300

[ui.window.box.scroll.list.item.icon]
pixel_size = 40
