close_when_open = true
force_keyboard_focus = true

theme = "launcher"
theme_base = []
theme_location = ["~/.config/walker/themes/"]

[list]
max_entries = 100

[search]
placeholder = " Search..."

# [builtins.hyprland_keybinds]
# hidden = true

[builtins.applications]
launch_prefix = "uwsm app -- "
placeholder = " Search..."
prioritize_new = false
context_aware = false
show_sub_when_single = false
history = false
hidden = true

[builtins.applications.actions]
hide_category = true

[builtins.bookmarks]
hidden = true

[[builtins.bookmarks.entries]]
label = "Kriogenia - Github"
url = "https://github.com/kriogenia"
keywords = ["kriogenia", "github"]

[builtins.calc]
name = "Calculator"
min_chars = 3
prefix = "="

# [builtins.windows]
# switcher_only = true
# hidden = true
#
# [builtins.clipboard]
# hidden = false
#
# [builtins.commands]
# hidden = true
#
# [builtins.custom_commands]
# hidden = true

[builtins.emojis]
name = "Emojis"
prefix = ":"

[builtins.symbols]
hidden = true
after_copy = ""

[builtins.finder]
name = "Files"
hidden = false
use_fd = true
cmd_alt = "xdg-open $(dirname ~/%RESULT%)"
preview_images = true
prefix = "."

