[v1]
"aoc-cli 0.5.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["aoc"]
"bottom 0.9.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["btm"]
"cargo-bump 1.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-bump"]
"cargo-expand 1.0.9 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-expand"]
"cargo-workspaces 0.2.44 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-workspaces",
    "cargo-ws",
]
"du-dust 0.8.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["dust"]
"exa 0.10.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["exa"]
"mdbook 0.4.21 (registry+https://github.com/rust-lang/crates.io-index)" = ["mdbook"]
"navi 2.20.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["navi"]
"rede 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["rede"]
"ripgrep 13.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rg"]
"seimdti 0.1.0 (path+file:///home/sotoestevez/Projects/web/sotoestevezdev/seimd/template_injector)" = ["seimdti"]
"tauri-cli 1.0.0-rc.10 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-tauri"]
"tlrc 1.8.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["tldr"]
"trunk 0.15.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["trunk"]
"ytop 0.6.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["ytop"]
