# Configures a given app installing its dependencies
# and setting the configuraitons
- name: "Install required packages"
  pacman:
    name: "{{ config.packages | default([]) }}"
    state: present
    update_cache: yes
- name: "Check folders"
  become_user: "{{ user }}"
  file:
    name: "$HOME/{{ item }}"
    state: directory
  loop: "{{ config.folders | default([]) }}"
- name: "Remove old configuration"
  become_user: "{{ user }}"
  file:
    name: "$HOME/{{ item }}"
    state: absent
  loop: "{{ config.links | default([]) }}"
- name: "Link new configuration"
  become_user: "{{ user }}"
  file:
    src: "$HOME/dotfiles/{{ item }}"
    dest: "$HOME/{{ item }}"
    state: link
  loop: "{{ config.links | default([]) }}"
