- name: Remove old .config folder
  become_user: "{{ user }}"
  file:
    name: "$HOME/.config/{{ configuration.name }}"
    state: absent
- name: Link .config configurations
  become_user: "{{ user }}"
  file:
    src: "$HOME/dotfiles/.config/{{ configuration.name }}"
    dest: "$HOME/.config/{{ configuration.name }}"
    state: link
