# symlinks library root folders to shared disk
---
- name: Symlink library folders
  hosts: localhost
  vars:
    shared:
      path: /mnt/shared
      filetype: ext4
      label: SHARED
    libraries:
      Documents: documents
      Downloads: downloads
      Music: audio
      Pictures: pictures
      Videos: videos
  tasks:
    - name: Create mount volume
      file:
        path: "{{ shared.path }}"
        state: directory
        mode: "0755"
    - name: Mount shared volume
      mount:
        path: "{{ shared.path }}"
        src: "LABEL={{ shared.label }}"
        fstype: "{{ shared.filetype }}"
        state: mounted
        opts: nosuid,nodev,nofail,x-gvfs-show,uid=1000,gid=1000
    - name: Remove preexisting folders
      file:
        path: "$HOME/{{ item.key }}"
        state: absent
      loop: "{{ libraries | dict2items }}"
    - name: Symlink folders
      file:
        src: "{{ shared.path }}/{{ item.value }}"
        dest: "$HOME/{{ item.key }}"
        state: link
      loop: "{{ libraries | dict2items }}"
