- name: Check folder
  become_user: "{{ user }}"
  file:
    name: "/home/{{ user }}/.{{ configuration.name }}"
    state: directory
- name: Check inner folders
  become_user: "{{ user }}"
  file:
    name: "/home/{{ user }}/.{{ configuration.name }}/{{ item }}"
    state: directory
  loop: "{{ configuration.folders | default([]) }}"
- name: Remove old files
  become_user: "{{ user }}"
  file:
    name: "/home/{{ user }}/.{{configuration.name }}/{{ item }}"
    state: absent
  loop: '{{ configuration.files }}'
- name: Symlink files
  become_user: "{{ user }}"
  file:
    src: "/home/{{ user }}/dotfiles/.{{configuration.name }}/{{ item }}"
    dest: "/home/{{ user }}/.{{ configuration.name }}/{{ item }}"
    state: link
  loop: '{{ configuration.files }}'
