- name: Check folders
  become_user: "{{ user }}"
  file:
    name: "$HOME/{{ item }}"
    state: directory
  loop: "{{ configuration.folders }}"
- name: Remove old files
  become_user: "{{ user }}"
  file:
    name: "$HOME/{{ item }}"
    state: absent
  loop: '{{ configuration.files }}'
- name: Symlink files
  become_user: "{{ user }}"
  file:
    src: "$HOME/dotfiles/{{ item }}"
    dest: "$HOME/{{ item }}"
    state: link
  loop: '{{ configuration.files }}'
