- name: Check for SDKMAN
  stat:
    path: "/home/{{ user }}/.sdkman"
  register: sdkman
- name: Install required packages
  pacman:
    name: "{{ configurations.sdkman.packages }}"
    state: present
    update_cache: yes
  when: not sdkman.stat.exists
- name: Install SDKMAN
  become_user: "{{ user }}"
  shell: |
    curl -s "https://get.sdkman.io" | bash
  when: not sdkman.stat.exists
