- name: Ensure yay dependencies are installed
  pacman:
    name:
      - base-devel
      - git
    state: present
- name: Clone yay repository from AUR
  become_user: "{{ user }}"
  git:
    repo: "https://aur.archlinux.org/yay.git"
    dest: "$HOME/yay"
    clone: yes
    update: yes
- name: Install yay from AUR
  become_user: "{{ user }}"
  command:
    cmd: makepkg -si --noconfirm
    chdir: "$HOME/yay"
    creates: "/usr/bin/yay"
- name: Clean up yay build directory
  become_user: "{{ user }}"
  file:
    path: "$HOME/yay"
    state: absent
- name: Create the ansible_yay user
  become: true
  user:
    name: ansible_yay
    group: wheel
    state: present
- name: Ensure sudoers directory exists
  file:
    path: "/etc/sudoers.d"
    state: directory
    mode: "0755"
- name: Configure sudoers for paswordless yay
  become: true
  copy:
    dest: "/etc/sudoers.d/11-install-ansible_yay"
    content: "ansible_yay ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    mode: "0640"
    validate: "visudo -cf %s"
